In [2]:
import pandas as pd
import numpy as np

data_df = pd.read_excel('fake_new_dataset.xlsx')

In [3]:
data_df

,Unnamed: 0,title,text,subcategory,label
0,0,FACEBOOK DELETES MICHIGAN ANTI-LOCKDOWN GROUP ...,Facebook has shuttered a popular group for Mic...,false news,0
1,1,Other Viewpoints: COVID-19 is worse than the flu,We can now officially put to rest all comparis...,true,1
2,2,Bermuda's COVID-19 cases surpass 100,The Ministry of Health in Bermuda has confirme...,true,1
3,3,Purdue University says students face 'close to...,"Purdue University President Mitch Daniels, the...",partially false,0
4,4,THE HIGH COST OF LOCKING DOWN AMERICA: “WE’VE ...,Locking down much of the country may have help...,false news,0
...,...,...,...,...,...
3114,2998,2019-nCoV: Health dept. on full alert,Quarantine advised for 80 persons across the S...,true,1
3115,2999,Screening machine for corona virus launched at...,South Sudan has begun screening all travelers ...,true,1
3116,3000,Coronavirus (2019-nCoV),Coronavirus (2019-nCoV) is a new respiratory i...,true,1
3117,3001,Characterizing Patients Hospitalized With COVI...,Characterizing Patients Hospitalized With COVI...,false news,0
3118,3002,Corona Virus WARNING,Just something to be prepared for… but then it...,false news,0

In [4]:
covid_val_df = pd.read_csv('val.tsv', sep='\t')

In [5]:
covid_val_df

                                                 title  true
0                Top Guidelines Of corona virus reddit     1
1                   2019 Novel Corona Virus(2019-nCoV)     1
2    AI Helping to Inform on the Corona Virus Outbreak     1
3          ‘Corona won’t affect chickens’, Health News     0
4    Dr. Brownstein: Corona Virus is Nothing New – ...     0
..                                                 ...   ...
619  TWO SEPARATE REPORTS CONFIRM ‘MOST INTEL AGENC...     0
620    We are ready for Corona virus should it arrive      1
621                          Manila Corona Virus Feb 7     0
622  Only 10% Of Pulses Promised Under COVID-19 Rel...     0
623  Detected a person infected with corona virus f...     1

[624 rows x 2 columns]

In [8]:
covid_val_df_fake = covid_val_df[covid_val_df['true'] == 0]

In [9]:
covid_val_df_fake

                                                 title  true
3          ‘Corona won’t affect chickens’, Health News     0
4    Dr. Brownstein: Corona Virus is Nothing New – ...     0
6           how Corona Virus patient shivers violently     0
8    Cepheid developing automated molecular test fo...     0
10   The case fatality rate of corona virus so far ...     0
..                                                 ...   ...
616  Scripps becomes first in region to treat COVID...     0
618  VIDEO: WOMAN DRIVEN OUT OF GROCERY STORE BY AN...     0
619  TWO SEPARATE REPORTS CONFIRM ‘MOST INTEL AGENC...     0
621                          Manila Corona Virus Feb 7     0
622  Only 10% Of Pulses Promised Under COVID-19 Rel...     0

[233 rows x 2 columns]

In [10]:
covid_val_df_fake['text'] = None

C:\Users\matti\AppData\Local\Temp\ipykernel_16120\346749705.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  covid_val_df_fake['text'] = None

In [11]:
covid_val_df_fake

                                                 title  true  text
3          ‘Corona won’t affect chickens’, Health News     0  None
4    Dr. Brownstein: Corona Virus is Nothing New – ...     0  None
6           how Corona Virus patient shivers violently     0  None
8    Cepheid developing automated molecular test fo...     0  None
10   The case fatality rate of corona virus so far ...     0  None
..                                                 ...   ...   ...
616  Scripps becomes first in region to treat COVID...     0  None
618  VIDEO: WOMAN DRIVEN OUT OF GROCERY STORE BY AN...     0  None
619  TWO SEPARATE REPORTS CONFIRM ‘MOST INTEL AGENC...     0  None
621                          Manila Corona Virus Feb 7     0  None
622  Only 10% Of Pulses Promised Under COVID-19 Rel...     0  None

[233 rows x 3 columns]

In [12]:
for i in range(len(covid_val_df_fake)):
    
    row = covid_val_df_fake.iloc[i]
    title = row.title
    
    original_row = data_df[data_df['title'] == title]
    original_text = original_row.text.values[0]
    
    covid_val_df_fake.iat[i, 2] = original_text

In [13]:
covid_val_df_fake

,title,true,text
3,"‘Corona won’t affect chickens’, Health News",0,A Representative image Visakhapatnam : Chairma...
4,Dr. Brownstein: Corona Virus is Nothing New – ...,0,I am sure you aware of the corona virus infect...
6,how Corona Virus patient shivers violently,0,A 15-second footage of deathly coronavirus pat...
8,Cepheid developing automated molecular test fo...,0,Cepheid said Monday that it is working on an a...
10,The case fatality rate of corona virus so far ...,0,"Do not panic, time to fight out The case fatal..."
...,...,...,...
616,Scripps becomes first in region to treat COVID...,0,Scripps Health has announced that they have su...
618,VIDEO: WOMAN DRIVEN OUT OF GROCERY STORE BY AN...,0,Video: Woman Driven Out of Grocery Store by An...
619,TWO SEPARATE REPORTS CONFIRM ‘MOST INTEL AGENC...,0,Two separate reports cited a senior intelligen...
621,Manila Corona Virus Feb 7,0,"Woke up this morning, and was feeling a lot of..."
622,Only 10% Of Pulses Promised Under COVID-19 Rel...,0,Pulses amounting to 1 kg per family which was ...

In [15]:
covid_val_df_fake['title'].isnull().sum()

0

In [16]:
covid_val_df_fake['text'].isnull().sum()

0

In [19]:
covid_val_df_fake = covid_val_df_fake.reset_index(drop=True)

In [20]:
covid_val_df_fake

,title,true,text
0,"‘Corona won’t affect chickens’, Health News",0,A Representative image Visakhapatnam : Chairma...
1,Dr. Brownstein: Corona Virus is Nothing New – ...,0,I am sure you aware of the corona virus infect...
2,how Corona Virus patient shivers violently,0,A 15-second footage of deathly coronavirus pat...
3,Cepheid developing automated molecular test fo...,0,Cepheid said Monday that it is working on an a...
4,The case fatality rate of corona virus so far ...,0,"Do not panic, time to fight out The case fatal..."
...,...,...,...
228,Scripps becomes first in region to treat COVID...,0,Scripps Health has announced that they have su...
229,VIDEO: WOMAN DRIVEN OUT OF GROCERY STORE BY AN...,0,Video: Woman Driven Out of Grocery Store by An...
230,TWO SEPARATE REPORTS CONFIRM ‘MOST INTEL AGENC...,0,Two separate reports cited a senior intelligen...
231,Manila Corona Virus Feb 7,0,"Woke up this morning, and was feeling a lot of..."
232,Only 10% Of Pulses Promised Under COVID-19 Rel...,0,Pulses amounting to 1 kg per family which was ...

In [21]:
json_fake_df = covid_val_df_fake

In [23]:
import json

domains = ["techcrunch.com", "vancouversun.com", "chicagotribune.com", "esquire.com",
           "mashable.com", "theguardian.com", "theatlantic.com", "slate.com"]

for i in range(len(json_fake_df)):
        
    domain = domains[i % 8]
    
    data = {
        "url" : "",
        "summary" : None,
        "authors" : [],
        "publish_date" : "04-19-2019",
        "status" : "success_wayback",
        "warc_date" : "20190424064330",
        "split":"gen",
        "inst_index" : 24030,
        "domain" : domain,
        "title" : json_fake_df.iloc[i].title,
        "text" : json_fake_df.iloc[i].text
    }
    
    with open('covid_fake_sample.jsonl', 'a') as f:
        f.write(json.dumps(data) + "\n")