In [1]:
import pandas as pd
import numpy as np

fake_df = pd.read_csv('News _dataset/Fake.csv')
true_df = pd.read_csv('News _dataset/True.csv')

In [2]:
display(fake_df)

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"
...,...,...,...,...
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016"
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016"
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016"
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016"
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016"

In [3]:
isot_val_df = pd.read_csv('val.tsv', sep='\t')

In [4]:
display(isot_val_df)

                                                  title  true
0     NBC REPORTER Asks Sarah Sanders About Taxes…Sh...     0
1     DEADBEATS BEWARE: Trump’s Food Stamp Reform Is...     0
2     Netanyahu, Trump align on Iran ahead of Israel...     1
3     TRUMP SUPPORTER Whose Brutal Beating By Black ...     0
4      Fox News FIRES Longtime Executive For Making ...     0
...                                                 ...   ...
8975  BRAINWASHED CHILDREN MOCK President Trump in D...     0
8976  U.S. 'strongly opposes' Iraqi Kurdish independ...     1
8977  GEORGE SOROS ADMITS He’s Behind Invasion Of Eu...     0
8978  Trump's threats chill corporate investment pla...     1
8979  COLLEGE PROFESSOR CAUGHT ON TAPE: You Can’t Ha...     0

[8980 rows x 2 columns]

In [5]:
isot_val_df_fake = isot_val_df[isot_val_df['true'] == 0]
isot_val_df_real = isot_val_df[isot_val_df['true'] == 1]

In [6]:
isot_val_df_fake

                                                  title  true
0     NBC REPORTER Asks Sarah Sanders About Taxes…Sh...     0
1     DEADBEATS BEWARE: Trump’s Food Stamp Reform Is...     0
3     TRUMP SUPPORTER Whose Brutal Beating By Black ...     0
4      Fox News FIRES Longtime Executive For Making ...     0
6     SOMALI PIRATE POSING AS A “REFUGEE” Found Cove...     0
...                                                 ...   ...
8970  UNHINGED! NANCY PELOSI’S DAUGHTER Blows Up At ...     0
8974   Facebook Troll EXCITED For Obamacare Repeal I...     0
8975  BRAINWASHED CHILDREN MOCK President Trump in D...     0
8977  GEORGE SOROS ADMITS He’s Behind Invasion Of Eu...     0
8979  COLLEGE PROFESSOR CAUGHT ON TAPE: You Can’t Ha...     0

[4653 rows x 2 columns]

In [7]:
isot_val_df_real

                                                  title  true
2     Netanyahu, Trump align on Iran ahead of Israel...     1
5     Congo and Uganda to launch joint operation aga...     1
9     Moscow tells Tehran Russia remains committed t...     1
12    White House asks Supreme Court to allow full t...     1
14    North Korea to release captured South Korea fi...     1
...                                                 ...   ...
8971  Republican Trump backed Iraq war in 2002 inter...     1
8972  Senate gives limited resources to Russia elect...     1
8973  Bahrain court sentences 10 men on terrorism ch...     1
8976  U.S. 'strongly opposes' Iraqi Kurdish independ...     1
8978  Trump's threats chill corporate investment pla...     1

[4327 rows x 2 columns]

In [8]:
isot_val_df_fake['text'] = None

C:\Users\mai5279\AppData\Local\Temp\ipykernel_356\129633218.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isot_val_df_fake['text'] = None

In [9]:
isot_val_df_fake

                                                  title  true  text
0     NBC REPORTER Asks Sarah Sanders About Taxes…Sh...     0  None
1     DEADBEATS BEWARE: Trump’s Food Stamp Reform Is...     0  None
3     TRUMP SUPPORTER Whose Brutal Beating By Black ...     0  None
4      Fox News FIRES Longtime Executive For Making ...     0  None
6     SOMALI PIRATE POSING AS A “REFUGEE” Found Cove...     0  None
...                                                 ...   ...   ...
8970  UNHINGED! NANCY PELOSI’S DAUGHTER Blows Up At ...     0  None
8974   Facebook Troll EXCITED For Obamacare Repeal I...     0  None
8975  BRAINWASHED CHILDREN MOCK President Trump in D...     0  None
8977  GEORGE SOROS ADMITS He’s Behind Invasion Of Eu...     0  None
8979  COLLEGE PROFESSOR CAUGHT ON TAPE: You Can’t Ha...     0  None

[4653 rows x 3 columns]

In [10]:
for i in range(len(isot_val_df_fake)):
    
    row = isot_val_df_fake.iloc[i]
    title = row.title
    
    original_row = fake_df[fake_df['title'] == title]
    original_text = original_row.text.values[0]
    
    isot_val_df_fake.iat[i, 2] = original_text

In [11]:
isot_val_df_fake

,title,true,text
0,NBC REPORTER Asks Sarah Sanders About Taxes…Sh...,0,Sarah Sanders does it again! The snarky DC rep...
1,DEADBEATS BEWARE: Trump’s Food Stamp Reform Is...,0,All we re hearing from the left is fear monger...
3,TRUMP SUPPORTER Whose Brutal Beating By Black ...,0,https://youtu.be/kKFQ5i9jXmA
4,Fox News FIRES Longtime Executive For Making ...,0,"For years, Fox News hosts have been spewing ra..."
6,SOMALI PIRATE POSING AS A “REFUGEE” Found Cove...,0,"Apparently free housing, food and spending mon..."
...,...,...,...
8970,UNHINGED! NANCY PELOSI’S DAUGHTER Blows Up At ...,0,
8974,Facebook Troll EXCITED For Obamacare Repeal I...,0,It what can only be seen as a situation where ...
8975,BRAINWASHED CHILDREN MOCK President Trump in D...,0,A disturbing video published by The Washington...
8977,GEORGE SOROS ADMITS He’s Behind Invasion Of Eu...,0,Soros isn t just a danger to America he s a da...
8979,COLLEGE PROFESSOR CAUGHT ON TAPE: You Can’t Ha...,0,Close your eyes and imagine a white professor ...

In [12]:
isot_val_df_fake['title'].isnull().sum()

0

In [13]:
isot_val_df_fake['text'].isnull().sum()

0

In [14]:
isot_val_df_fake = isot_val_df_fake.reset_index(drop=True)

In [15]:
isot_val_df_fake

,title,true,text
0,NBC REPORTER Asks Sarah Sanders About Taxes…Sh...,0,Sarah Sanders does it again! The snarky DC rep...
1,DEADBEATS BEWARE: Trump’s Food Stamp Reform Is...,0,All we re hearing from the left is fear monger...
2,TRUMP SUPPORTER Whose Brutal Beating By Black ...,0,https://youtu.be/kKFQ5i9jXmA
3,Fox News FIRES Longtime Executive For Making ...,0,"For years, Fox News hosts have been spewing ra..."
4,SOMALI PIRATE POSING AS A “REFUGEE” Found Cove...,0,"Apparently free housing, food and spending mon..."
...,...,...,...
4648,UNHINGED! NANCY PELOSI’S DAUGHTER Blows Up At ...,0,
4649,Facebook Troll EXCITED For Obamacare Repeal I...,0,It what can only be seen as a situation where ...
4650,BRAINWASHED CHILDREN MOCK President Trump in D...,0,A disturbing video published by The Washington...
4651,GEORGE SOROS ADMITS He’s Behind Invasion Of Eu...,0,Soros isn t just a danger to America he s a da...
4652,COLLEGE PROFESSOR CAUGHT ON TAPE: You Can’t Ha...,0,Close your eyes and imagine a white professor ...

In [16]:
json_fake_df = isot_val_df_fake.sample(frac=0.1)
json_fake_df = json_fake_df.reset_index(drop=True)

In [17]:
json_fake_df

,title,true,text
0,Trump Has NEVER Looked So Incompetent; His Ch...,0,With every new detail revealing itself about D...
1,WATCH: Don Lemon CRUSHES Trump Supporter For ...,0,Trump mouthpiece Kayleigh McEnany just made th...
2,Twitter HUMILIATES Trump For Bragging About G...,0,Donald Trump probably should have just let thi...
3,WATCH: Giuliani Demands That Democrats Apolog...,0,"You know, because in fantasyland Republicans n..."
4,NOTE TO SATURDAY NIGHT LIVE: Making Fun Of Tru...,0,
...,...,...,...
460,DALLAS MAIDAN: Staged Snipers Designed to Infl...,0,"Daily Shooter 21st Century WireLast night, a h..."
461,CROWD OF GERMAN PATRIOTS Greets Merkel Shoutin...,0,Merkel was booed by residents of Saxony who re...
462,Watch The Unedited VIDEO Of Oregon Militiaman...,0,WARNING: Disturbing image of a man being shot....
463,Staffers INSIDE The White House Are Showing U...,0,"Last week, a ton of U.S. government employees ..."
464,ROSIE O’DONNELL Gets A Tongue Lashing For Her ...,0,

In [18]:
import json

domains = ["techcrunch.com", "vancouversun.com", "chicagotribune.com", "esquire.com",
           "mashable.com", "theguardian.com", "theatlantic.com", "slate.com"]

for i in range(len(json_fake_df)):
        
    domain = domains[i % 8]
    
    data = {
        "url" : "",
        "summary" : None,
        "authors" : [],
        "publish_date" : "04-19-2019",
        "status" : "success_wayback",
        "warc_date" : "20190424064330",
        "split":"gen",
        "inst_index" : 24030,
        "domain" : domain,
        "title" : json_fake_df.iloc[i].title,
        "text" : json_fake_df.iloc[i].text
    }
    
    with open('isot_fake_sample.jsonl', 'a') as f:
        f.write(json.dumps(data) + "\n")